# Generated by Django 4.1.4 on 2022-12-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('EmailAddress', models.CharField(max_length=55)),
                ('City', models.CharField(max_length=55)),
                ('Country', models.CharField(max_length=55)),
            ],
        ),
    ]
